services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    image: tumktp/e-commerce-backend:latest  
    ports:
      - "5000:5000"  
    environment:
      DATABASE_URL: postgresql://test:test@db:5432/test  
      PORT: 5000
      JWT_SECRET: acvpndqsghl=jhdpbnojkp23-avc
      JWT_EXPIRES_IN: 7d
    depends_on:
      - db 
